sudo: required

services:
  - docker

before_install:
  - docker build -t programmingboy/docker-react  .

script:
  - docker run -e CI=true programmingboy/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-156152334714"
    bucket_path: "docker"
    on:
      branch: main
    access_key_id: $KEYID
    secret_access_key: $SECRET